In [2]:
import pandas as pd
import numpy as np


1) Write a function so that the columns of the output matrix are powers of the inputvector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1.

HINT:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  Alexandre-Theophile Vandermonde.

2) **Problem Statement** 

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:The moving average sequence has n-k+1 elements as shown below.The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1  2  3  4  5  6  7  8  9 10

======= == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100 

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question:Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
# 1)

def myvander(arr, N):
    x = np.array([arr ** (N - 1 - i) for i in range(N)])
    arrays = []
    for j in x:
        arr = np.array(j)
        if arr.ndim < 2:
            arr = np.array(arr, copy=False, subok=True, ndmin=2).T
        arrays.append(arr)
    print("\nAssignment Vander function - \n", np.concatenate(arrays, 1))


arr = np.array([1, 2, 3])
N = 3
myvander(arr, N)



Assignment Vander function - 
 [[1 1 1]
 [4 2 1]
 [9 3 1]]


In [5]:
def moving_avg(sequence, k):
    n = len(sequence)
    y = (n - k) + 1
    a = k
    print("i  - ", [j for j in range(1, len(sequence)+1)])
    print("="*50)
    print("Input  - ", [l for l in sequence])
    for i in range(y):
        lst = sequence[i:a]
        print("y"+str(i)+"  ", int(sum(lst) / k))
        a += 1


sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
print("\nAverage window moving - ")
moving_avg(sequence, k)



Average window moving - 
i  -  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
Input  -  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
y0   5
y1   4
y2   5
y3   6
y4   9
y5   28
y6   49
y7   72
y8   84
y9   93
y10   116
